# Basic Decision Tree for classification

## Imports

In [2]:
from sklearn import tree
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

import numpy as np
import pandas as pd

## Exploring the data

In [3]:
titanic_dataset = pd.read_csv("../../data/titanic/Titanic-Dataset.csv",index_col="PassengerId")
titanic_dataset.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [4]:
titanic_dataset.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic_dataset.iloc[:5,:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
titanic_dataset.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

## Naive approach

### Separating data into train and test

In [7]:
predictors, target = titanic_dataset.iloc[:, 1:], titanic_dataset.iloc[:, :1]
predictors_train, predictors_test, target_train, target_test = train_test_split(predictors, target, random_state=123)
target_train.head()

             Survived
PassengerId
661                 1
853                 0
704                 0
887                 0
526                 0

### Training tree clasifier model

In [8]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(predictors_train, target_train)

ValueError: could not convert string to float: 'Frauenthal, Dr. Henry William'

### What happened
The error we are seeing is where sklearn is trying to convert a string value into a float.
Models tend to prefer a single type of input data. In our case, we have strings, floats and int datatypes.
What we should do is instead turn everything that we can into floats

## Less naive approach

### Preparing data

In [9]:
titanic_dataset_preprocessed = titanic_dataset.copy(deep=True)

In [10]:
titanic_dataset_preprocessed["Sex"] = (titanic_dataset_preprocessed["Sex"]=="male").astype("float64")

In [11]:
titanic_dataset_preprocessed.describe()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,0.647587,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,0.477990,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,0.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,1.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,1.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200

In [12]:
titanic_dataset_preprocessed.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",1.0,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0.0,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",0.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0.0,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",1.0,35.0,0,0,373450,8.0500,NaN,S

In [13]:
print("Number of unique ticket values: ", titanic_dataset_preprocessed["Ticket"].nunique())
print("Number of unique cabin values: ", titanic_dataset_preprocessed["Cabin"].nunique())
print("Number of unique embarked values: ",titanic_dataset_preprocessed["Embarked"].nunique())

Number of unique ticket values:  681
Number of unique cabin values:  147
Number of unique embarked values:  3

In [14]:
titanic_dataset_preprocessed = titanic_dataset_preprocessed.drop(["Name", "Ticket", "Cabin"], axis=1)

In [15]:
titanic_dataset_preprocessed

             Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
PassengerId
1                   0       3  1.0  22.0      1      0   7.2500        S
2                   1       1  0.0  38.0      1      0  71.2833        C
3                   1       3  0.0  26.0      0      0   7.9250        S
4                   1       1  0.0  35.0      1      0  53.1000        S
5                   0       3  1.0  35.0      0      0   8.0500        S
...               ...     ...  ...   ...    ...    ...      ...      ...
887                 0       2  1.0  27.0      0      0  13.0000        S
888                 1       1  0.0  19.0      0      0  30.0000        S
889                 0       3  0.0   NaN      1      2  23.4500        S
890                 1       1  1.0  26.0      0      0  30.0000        C
891                 0       3  1.0  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [16]:
titanic_dataset_preprocessed = pd.get_dummies(titanic_dataset_preprocessed).astype("Float64").dropna()

### Separating data into test and train

In [17]:
predictors, target = titanic_dataset_preprocessed.iloc[:, 1:], titanic_dataset_preprocessed.iloc[:, :1]
predictors_train, predictors_test, target_train, target_test = train_test_split(predictors, target, random_state=123)
predictors_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
PassengerId,,,,,,,,,
87,3.0,1.0,16.0,1.0,3.0,34.375,0.0,0.0,1.0
185,3.0,0.0,4.0,0.0,2.0,22.025,0.0,0.0,1.0
407,3.0,1.0,51.0,0.0,0.0,7.75,0.0,0.0,1.0
286,3.0,1.0,33.0,0.0,0.0,8.6625,1.0,0.0,0.0
592,1.0,0.0,52.0,1.0,0.0,78.2667,1.0,0.0,0.0

In [18]:
target_test.head()

             Survived
PassengerId
652               1.0
695               0.0
798               1.0
876               1.0
506               0.0

In [19]:
clf = tree.DecisionTreeClassifier(max_leaf_nodes=5, max_depth=5)
clf = clf.fit(predictors_train, target_train)

### Accuracy

In [20]:
target_test.iloc[:, 0]
# predictors_test.iloc[1, :]

PassengerId
652    1.0
695    0.0
798    1.0
876    1.0
506    0.0
      ...
131    0.0
875    1.0
377    1.0
821    1.0
487    1.0
Name: Survived, Length: 179, dtype: Float64

In [48]:
# predictions = np.zeros(predictions.shape, np.float64)
predictions = clf.predict(predictors_test)

In [49]:
n = 0
correct = 0
for prediction in predictions:
    correct += int(prediction==target_test.iloc[n, 0])
    n += 1

print("Accuracy rate: ", (correct)/n)
print("Total number of guesses: ", n)

Accuracy rate:  0.7932960893854749
Total number of guesses:  179

In [50]:
true_positive = 0
true_negative = 0
false_positive = 0
false_negative = 0
predictions = clf.predict(predictors_test)

for i, prediction in enumerate(predictions):
    if prediction == target_test.iloc[i, 0]:
        if prediction:
            true_positive += 1
        else:
            true_negative += 1
    else:
        if prediction:
            false_positive += 1
        else:
            false_negative += 1

print("Accuracy rate: ", (correct)/n)
print("Total number of guesses: ", n)
print("Confusion matrix:")
print(f"True positive: {true_positive} \t False negative: {false_negative}")
print(f"False positive: {false_positive} \t True negative: {true_negative}")

Accuracy rate:  0.7932960893854749
Total number of guesses:  179
Confusion matrix:
True positive: 35 	 False negative: 36
False positive: 1 	 True negative: 107